//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace Sextant.Services.Esi
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class EsiClient
    {
        private System.Net.Http.HttpClient _httpClient;
        private static System.Lazy<System.Text.Json.JsonSerializerOptions> _settings = new System.Lazy<System.Text.Json.JsonSerializerOptions>(CreateSerializerSettings, true);
        private System.Text.Json.JsonSerializerOptions _instanceSettings;

    #pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
        public EsiClient(System.Net.Http.HttpClient httpClient)
    #pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
        {
            _httpClient = httpClient;
            Initialize();
        }

        private static System.Text.Json.JsonSerializerOptions CreateSerializerSettings()
        {
            var settings = new System.Text.Json.JsonSerializerOptions();
            UpdateJsonSerializerSettings(settings);
            return settings;
        }

        protected System.Text.Json.JsonSerializerOptions JsonSerializerSettings { get { return _instanceSettings ?? _settings.Value; } }

        static partial void UpdateJsonSerializerSettings(System.Text.Json.JsonSerializerOptions settings);

        partial void Initialize();

        partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, string url);
        partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, System.Text.StringBuilder urlBuilder);
        partial void ProcessResponse(System.Net.Http.HttpClient client, System.Net.Http.HttpResponseMessage response);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Retrieve the uptime and player counts
        /// </summary>
        /// <remarks>
        /// EVE Server status
        /// <br/>
        /// <br/>---
        /// <br/>Alternate route: `/dev/status/`
        /// <br/>
        /// <br/>Alternate route: `/legacy/status/`
        /// <br/>
        /// <br/>Alternate route: `/v1/status/`
        /// <br/>
        /// <br/>Alternate route: `/v2/status/`
        /// <br/>
        /// <br/>---
        /// <br/>This route is cached for up to 30 seconds
        /// </remarks>
        /// <param name="datasource">The server name you would like data from</param>
        /// <param name="if_None_Match">ETag from a previous request. A 304 will be returned if this matches the current ETag</param>
        /// <returns>Server status</returns>
        /// <exception cref="EsiApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<Get_status_ok> Get_statusAsync(Datasource? datasource = null, string? if_None_Match = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {

                    if (if_None_Match != null)
                        request_.Headers.TryAddWithoutValidation("If-None-Match", ConvertToString(if_None_Match, System.Globalization.CultureInfo.InvariantCulture));
                    request_.Method = new System.Net.Http.HttpMethod("GET");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();

                    // Operation Path: "status/"
                    urlBuilder_.Append("status/");
                    urlBuilder_.Append('?');
                    if (datasource != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("datasource")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(datasource, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    urlBuilder_.Length--;

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Get_status_ok>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new EsiApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        if (status_ == 304)
                        {
                            string responseText_ = ( response_.Content == null ) ? string.Empty : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new EsiApiException("Not modified", status_, responseText_, headers_, null);
                        }
                        else
                        if (status_ == 400)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Bad_request>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new EsiApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new EsiApiException<Bad_request>("Bad request", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        if (status_ == 420)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Error_limited>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new EsiApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new EsiApiException<Error_limited>("Error limited", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        if (status_ == 500)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Internal_server_error>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new EsiApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new EsiApiException<Internal_server_error>("Internal server error", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        if (status_ == 503)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Service_unavailable>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new EsiApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new EsiApiException<Service_unavailable>("Service unavailable", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        if (status_ == 504)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Gateway_timeout>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new EsiApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new EsiApiException<Gateway_timeout>("Gateway timeout", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new EsiApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Get type information
        /// </summary>
        /// <remarks>
        /// Get information on a type
        /// <br/>
        /// <br/>---
        /// <br/>Alternate route: `/dev/universe/types/{type_id}/`
        /// <br/>
        /// <br/>Alternate route: `/legacy/universe/types/{type_id}/`
        /// <br/>
        /// <br/>Alternate route: `/v2/universe/types/{type_id}/`
        /// <br/>
        /// <br/>Alternate route: `/v3/universe/types/{type_id}/`
        /// <br/>
        /// <br/>---
        /// <br/>This route expires daily at 11:05
        /// </remarks>
        /// <param name="type_id">An Eve item type ID</param>
        /// <param name="accept_Language">Language to use in the response</param>
        /// <param name="datasource">The server name you would like data from</param>
        /// <param name="if_None_Match">ETag from a previous request. A 304 will be returned if this matches the current ETag</param>
        /// <param name="language">Language to use in the response, takes precedence over Accept-Language</param>
        /// <returns>Information about a type</returns>
        /// <exception cref="EsiApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<Get_universe_types_type_id_ok> Get_universe_types_type_idAsync(int type_id, AcceptLanguage? accept_Language = null, Datasource? datasource = null, string? if_None_Match = null, Language? language = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            if (type_id == null)
                throw new System.ArgumentNullException("type_id");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {

                    if (accept_Language != null)
                        request_.Headers.TryAddWithoutValidation("Accept-Language", ConvertToString(accept_Language, System.Globalization.CultureInfo.InvariantCulture));

                    if (if_None_Match != null)
                        request_.Headers.TryAddWithoutValidation("If-None-Match", ConvertToString(if_None_Match, System.Globalization.CultureInfo.InvariantCulture));
                    request_.Method = new System.Net.Http.HttpMethod("GET");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();

                    // Operation Path: "universe/types/{type_id}/"
                    urlBuilder_.Append("universe/types/");
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(type_id, System.Globalization.CultureInfo.InvariantCulture)));
                    urlBuilder_.Append('/');
                    urlBuilder_.Append('?');
                    if (datasource != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("datasource")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(datasource, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (language != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("language")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(language, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    urlBuilder_.Length--;

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Get_universe_types_type_id_ok>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new EsiApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        if (status_ == 304)
                        {
                            string responseText_ = ( response_.Content == null ) ? string.Empty : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new EsiApiException("Not modified", status_, responseText_, headers_, null);
                        }
                        else
                        if (status_ == 400)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Bad_request>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new EsiApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new EsiApiException<Bad_request>("Bad request", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        if (status_ == 404)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Response>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new EsiApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new EsiApiException<Response>("Type not found", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        if (status_ == 420)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Error_limited>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new EsiApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new EsiApiException<Error_limited>("Error limited", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        if (status_ == 500)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Internal_server_error>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new EsiApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new EsiApiException<Internal_server_error>("Internal server error", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        if (status_ == 503)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Service_unavailable>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new EsiApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new EsiApiException<Service_unavailable>("Service unavailable", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        if (status_ == 504)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Gateway_timeout>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new EsiApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new EsiApiException<Gateway_timeout>("Gateway timeout", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new EsiApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        protected struct ObjectResponseResult<T>
        {
            public ObjectResponseResult(T responseObject, string responseText)
            {
                this.Object = responseObject;
                this.Text = responseText;
            }

            public T Object { get; }

            public string Text { get; }
        }

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        private static System.Threading.Tasks.Task<string> ReadAsStringAsync(System.Net.Http.HttpContent content, System.Threading.CancellationToken cancellationToken)
        {
    #if NET5_0_OR_GREATER
            return content.ReadAsStringAsync(cancellationToken);
    #else
            return content.ReadAsStringAsync();
    #endif
        }

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        private static System.Threading.Tasks.Task<System.IO.Stream> ReadAsStreamAsync(System.Net.Http.HttpContent content, System.Threading.CancellationToken cancellationToken)
        {
    #if NET5_0_OR_GREATER
            return content.ReadAsStreamAsync(cancellationToken);
    #else
            return content.ReadAsStreamAsync();
    #endif
        }

        public bool ReadResponseAsString { get; set; }

        protected virtual async System.Threading.Tasks.Task<ObjectResponseResult<T>> ReadObjectResponseAsync<T>(System.Net.Http.HttpResponseMessage response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Threading.CancellationToken cancellationToken)
        {
            if (response == null || response.Content == null)
            {
                return new ObjectResponseResult<T>(default(T)!, string.Empty);
            }

            if (ReadResponseAsString)
            {
                var responseText = await ReadAsStringAsync(response.Content, cancellationToken).ConfigureAwait(false);
                try
                {
                    var typedBody = System.Text.Json.JsonSerializer.Deserialize<T>(responseText, JsonSerializerSettings);
                    return new ObjectResponseResult<T>(typedBody!, responseText);
                }
                catch (System.Text.Json.JsonException exception)
                {
                    var message = "Could not deserialize the response body string as " + typeof(T).FullName + ".";
                    throw new EsiApiException(message, (int)response.StatusCode, responseText, headers, exception);
                }
            }
            else
            {
                try
                {
                    using (var responseStream = await ReadAsStreamAsync(response.Content, cancellationToken).ConfigureAwait(false))
                    {
                        var typedBody = await System.Text.Json.JsonSerializer.DeserializeAsync<T>(responseStream, JsonSerializerSettings, cancellationToken).ConfigureAwait(false);
                        return new ObjectResponseResult<T>(typedBody!, string.Empty);
                    }
                }
                catch (System.Text.Json.JsonException exception)
                {
                    var message = "Could not deserialize the response body stream as " + typeof(T).FullName + ".";
                    throw new EsiApiException(message, (int)response.StatusCode, string.Empty, headers, exception);
                }
            }
        }

        private string ConvertToString(object? value, System.Globalization.CultureInfo cultureInfo)
        {
            if (value == null)
            {
                return "";
            }

            if (value is System.Enum)
            {
                var name = System.Enum.GetName(value.GetType(), value);
                if (name != null)
                {
                    var field_ = System.Reflection.IntrospectionExtensions.GetTypeInfo(value.GetType()).GetDeclaredField(name);
                    if (field_ != null)
                    {
                        var attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(field_, typeof(System.Runtime.Serialization.EnumMemberAttribute))
                            as System.Runtime.Serialization.EnumMemberAttribute;
                        if (attribute != null)
                        {
                            return attribute.Value != null ? attribute.Value : name;
                        }
                    }

                    var converted = System.Convert.ToString(System.Convert.ChangeType(value, System.Enum.GetUnderlyingType(value.GetType()), cultureInfo));
                    return converted == null ? string.Empty : converted;
                }
            }
            else if (value is bool)
            {
                return System.Convert.ToString((bool)value, cultureInfo).ToLowerInvariant();
            }
            else if (value is byte[])
            {
                return System.Convert.ToBase64String((byte[]) value);
            }
            else if (value is string[])
            {
                return string.Join(",", (string[])value);
            }
            else if (value.GetType().IsArray)
            {
                var valueArray = (System.Array)value;
                var valueTextArray = new string[valueArray.Length];
                for (var i = 0; i < valueArray.Length; i++)
                {
                    valueTextArray[i] = ConvertToString(valueArray.GetValue(i), cultureInfo);
                }
                return string.Join(",", valueTextArray);
            }

            var result = System.Convert.ToString(value, cultureInfo);
            return result == null ? "" : result;
        }
    }

    /// <summary>
    /// Bad request model
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Bad_request
    {

        /// <summary>
        /// Bad request message
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("error")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Error { get; set; } = default!;

    }

    /// <summary>
    /// Error limited model
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Error_limited
    {

        /// <summary>
        /// Error limited message
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("error")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Error { get; set; } = default!;

    }

    /// <summary>
    /// Forbidden model
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Forbidden
    {

        /// <summary>
        /// Forbidden message
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("error")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Error { get; set; } = default!;

        /// <summary>
        /// status code received from SSO
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("sso_status")]
        public int? Sso_status { get; set; } = default!;

    }

    /// <summary>
    /// Gateway timeout model
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Gateway_timeout
    {

        /// <summary>
        /// Gateway timeout message
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("error")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Error { get; set; } = default!;

        /// <summary>
        /// number of seconds the request was given
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("timeout")]
        public int? Timeout { get; set; } = default!;

    }

    /// <summary>
    /// Internal server error model
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Internal_server_error
    {

        /// <summary>
        /// Internal server error message
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("error")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Error { get; set; } = default!;

    }

    /// <summary>
    /// Service unavailable model
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Service_unavailable
    {

        /// <summary>
        /// Service unavailable message
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("error")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Error { get; set; } = default!;

    }

    /// <summary>
    /// Unauthorized model
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Unauthorized
    {

        /// <summary>
        /// Unauthorized message
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("error")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Error { get; set; } = default!;

    }

    /// <summary>
    /// The server name you would like data from
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum Datasource
    {

        [System.Runtime.Serialization.EnumMember(Value = @"tranquility")]
        Tranquility = 0,

    }

    /// <summary>
    /// Language to use in the response
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum AcceptLanguage
    {

        [System.Runtime.Serialization.EnumMember(Value = @"en")]
        En = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"en-us")]
        EnUs = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"de")]
        De = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"fr")]
        Fr = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"ja")]
        Ja = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"ru")]
        Ru = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"zh")]
        Zh = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"ko")]
        Ko = 7,

        [System.Runtime.Serialization.EnumMember(Value = @"es")]
        Es = 8,

    }

    /// <summary>
    /// Language to use in the response, takes precedence over Accept-Language
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum Language
    {

        [System.Runtime.Serialization.EnumMember(Value = @"en")]
        En = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"en-us")]
        EnUs = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"de")]
        De = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"fr")]
        Fr = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"ja")]
        Ja = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"ru")]
        Ru = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"zh")]
        Zh = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"ko")]
        Ko = 7,

        [System.Runtime.Serialization.EnumMember(Value = @"es")]
        Es = 8,

    }

    /// <summary>
    /// 200 ok object
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Get_status_ok
    {

        /// <summary>
        /// Current online player count
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("players")]
        public int Players { get; set; } = default!;

        /// <summary>
        /// Running version as string
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("server_version")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Server_version { get; set; } = default!;

        /// <summary>
        /// Server start timestamp
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("start_time")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset Start_time { get; set; } = default!;

        /// <summary>
        /// If the server is in VIP mode
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("vip")]
        public bool? Vip { get; set; } = default!;

    }

    /// <summary>
    /// 200 ok object
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Get_universe_types_type_id_ok
    {

        /// <summary>
        /// capacity number
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("capacity")]
        public float? Capacity { get; set; } = default!;

        /// <summary>
        /// description string
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("description")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Description { get; set; } = default!;

        /// <summary>
        /// dogma_attributes array
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("dogma_attributes")]
        [System.ComponentModel.DataAnnotations.MaxLength(1000)]
        public System.Collections.Generic.ICollection<Dogma_attributes>? Dogma_attributes { get; set; } = default!;

        /// <summary>
        /// dogma_effects array
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("dogma_effects")]
        [System.ComponentModel.DataAnnotations.MaxLength(1000)]
        public System.Collections.Generic.ICollection<Dogma_effects>? Dogma_effects { get; set; } = default!;

        /// <summary>
        /// graphic_id integer
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("graphic_id")]
        public int? Graphic_id { get; set; } = default!;

        /// <summary>
        /// group_id integer
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("group_id")]
        public int Group_id { get; set; } = default!;

        /// <summary>
        /// icon_id integer
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("icon_id")]
        public int? Icon_id { get; set; } = default!;

        /// <summary>
        /// This only exists for types that can be put on the market
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("market_group_id")]
        public int? Market_group_id { get; set; } = default!;

        /// <summary>
        /// mass number
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("mass")]
        public float? Mass { get; set; } = default!;

        /// <summary>
        /// name string
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("name")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Name { get; set; } = default!;

        /// <summary>
        /// packaged_volume number
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("packaged_volume")]
        public float? Packaged_volume { get; set; } = default!;

        /// <summary>
        /// portion_size integer
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("portion_size")]
        public int? Portion_size { get; set; } = default!;

        /// <summary>
        /// published boolean
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("published")]
        public bool Published { get; set; } = default!;

        /// <summary>
        /// radius number
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("radius")]
        public float? Radius { get; set; } = default!;

        /// <summary>
        /// type_id integer
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("type_id")]
        public int Type_id { get; set; } = default!;

        /// <summary>
        /// volume number
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("volume")]
        public float? Volume { get; set; } = default!;

    }

    /// <summary>
    /// Not found
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Response
    {

        /// <summary>
        /// Not found message
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("error")]
        public string? Error { get; set; } = default!;

    }

    /// <summary>
    /// dogma_attribute object
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Dogma_attributes
    {

        /// <summary>
        /// attribute_id integer
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("attribute_id")]
        public int Attribute_id { get; set; } = default!;

        /// <summary>
        /// value number
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("value")]
        public float Value { get; set; } = default!;

    }

    /// <summary>
    /// dogma_effect object
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Dogma_effects
    {

        /// <summary>
        /// effect_id integer
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("effect_id")]
        public int Effect_id { get; set; } = default!;

        /// <summary>
        /// is_default boolean
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("is_default")]
        public bool Is_default { get; set; } = default!;

    }



    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class EsiApiException : System.Exception
    {
        public int StatusCode { get; private set; }

        public string? Response { get; private set; }

        public System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

        public EsiApiException(string message, int statusCode, string? response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Exception? innerException)
            : base(message + "\n\nStatus: " + statusCode + "\nResponse: \n" + ((response == null) ? "(null)" : response.Substring(0, response.Length >= 512 ? 512 : response.Length)), innerException)
        {
            StatusCode = statusCode;
            Response = response;
            Headers = headers;
        }

        public override string ToString()
        {
            return string.Format("HTTP Response: \n\n{0}\n\n{1}", Response, base.ToString());
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class EsiApiException<TResult> : EsiApiException
    {
        public TResult Result { get; private set; }

        public EsiApiException(string message, int statusCode, string? response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, TResult result, System.Exception? innerException)
            : base(message, statusCode, response, headers, innerException)
        {
            Result = result;
        }
    }

}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765
