// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sextant.Data;

#nullable disable

namespace Sextant.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Sextant.Models.ActivityEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SystemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ActivityEvents");
                });

            modelBuilder.Entity("Sextant.Models.ChainConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EolAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LifetimeHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MassStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("MaxJumpMassKg")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MaxMassKg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WormholeTypeCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetSystemId");

                    b.HasIndex("SourceSystemId", "TargetSystemId");

                    b.ToTable("ChainConnections");
                });

            modelBuilder.Entity("Sextant.Models.ChainSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClassNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Effect")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SolarSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Statics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SolarSystemId");

                    b.ToTable("ChainSystems");
                });

            modelBuilder.Entity("Sextant.Models.CharacterToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CorporationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastRefreshed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("CharacterTokens");
                });

            modelBuilder.Entity("Sextant.Models.SdeRefreshRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WormholeSystemCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WormholeTypeCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SdeRefreshRuns");
                });

            modelBuilder.Entity("Sextant.Models.Signature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChainSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EolAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ScanPercentage")
                        .HasColumnType("TEXT");

                    b.Property<long>("ScannedByCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScannedByCharacterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChainSystemId", "SignatureId")
                        .IsUnique();

                    b.ToTable("Signatures");
                });

            modelBuilder.Entity("Sextant.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<long>("PrimaryCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sextant.Models.WormholeSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClassNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Effect")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsShattered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryName")
                        .HasColumnType("TEXT");

                    b.Property<long>("SolarSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Statics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SolarSystemId")
                        .IsUnique();

                    b.ToTable("WormholeSystems");
                });

            modelBuilder.Entity("Sextant.Models.WormholeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DestinationClass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EveTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LifetimeHours")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MaxJumpMassKg")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MaxMassKg")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ScanStrength")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("WormholeTypes");
                });

            modelBuilder.Entity("Sextant.Models.ChainConnection", b =>
                {
                    b.HasOne("Sextant.Models.ChainSystem", "SourceSystem")
                        .WithMany("SourceConnections")
                        .HasForeignKey("SourceSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sextant.Models.ChainSystem", "TargetSystem")
                        .WithMany("TargetConnections")
                        .HasForeignKey("TargetSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceSystem");

                    b.Navigation("TargetSystem");
                });

            modelBuilder.Entity("Sextant.Models.CharacterToken", b =>
                {
                    b.HasOne("Sextant.Models.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sextant.Models.Signature", b =>
                {
                    b.HasOne("Sextant.Models.ChainSystem", "ChainSystem")
                        .WithMany("Signatures")
                        .HasForeignKey("ChainSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChainSystem");
                });

            modelBuilder.Entity("Sextant.Models.ChainSystem", b =>
                {
                    b.Navigation("Signatures");

                    b.Navigation("SourceConnections");

                    b.Navigation("TargetConnections");
                });

            modelBuilder.Entity("Sextant.Models.User", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
