// AUTO-GENERATED by NSwag — do not edit manually.
// Run `nswag run` from the project root to regenerate.
//
// This is a placeholder until the backend OpenAPI spec is available.
// After running the backend, execute: nswag run

export interface ActivityEvent {
  id: number;
  type: string;
  characterId: number;
  characterName: string;
  summary: string;
  detailJson?: string;
  timestamp: string;
  systemId?: number;
}
